# Generated by Django 4.2.3 on 2023-08-12 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='New', max_length=35)),
                ('img2', models.ImageField(upload_to='ampmedia/img')),
                ('img', models.ImageField(upload_to='ampmedia/img')),
                ('content', models.TextField()),
            ],
            options={
                'verbose_name': 'about',
            },
        ),
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('adLink', models.URLField()),
            ],
            options={
                'verbose_name': 'Advert',
                'verbose_name_plural': 'Adverts',
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authorImg', models.ImageField(upload_to='ampmedia/img')),
                ('name', models.CharField(default='New', max_length=35)),
                ('img', models.ImageField(upload_to='ampmedia/img')),
                ('blogContent', models.TextField(max_length=120)),
                ('blogName', models.CharField(max_length=20)),
                ('date', models.DateField(auto_now_add=True)),
                ('author', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'blog',
                'verbose_name_plural': 'blogs',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='New', max_length=35)),
                ('img', models.ImageField(upload_to='ampmedia/img')),
                ('addressUrl', models.URLField()),
                ('address', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'contact',
                'verbose_name_plural': 'contacts',
            },
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseTitle', models.CharField(max_length=100)),
                ('courseChoices', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'course',
                'verbose_name_plural': 'courses',
            },
        ),
        migrations.CreateModel(
            name='Fact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numb', models.IntegerField()),
                ('content', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FAQs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=20)),
                ('answer', models.TextField()),
            ],
            options={
                'verbose_name': 'faq',
                'verbose_name_plural': 'faqs',
            },
        ),
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'feedback',
                'verbose_name_plural': 'feedbacks',
            },
        ),
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram_handle', models.URLField(blank=True, null=True)),
                ('facebook_handle', models.URLField(blank=True, null=True)),
                ('linkedin_handle', models.URLField(blank=True, null=True)),
                ('twitter_handle', models.URLField(blank=True, null=True)),
                ('github_handle', models.URLField(blank=True, null=True)),
                ('name', models.CharField(default='New', max_length=35)),
                ('siteName', models.CharField(max_length=35)),
                ('note', models.CharField(max_length=35)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'foot',
                'verbose_name_plural': 'footer',
            },
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('use_of_info_li', models.TextField(blank=True, null=True)),
                ('info_share_li', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Point',
                'verbose_name_plural': 'Points',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('value', models.CharField(default=False, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='New', max_length=35)),
                ('img', models.ImageField(upload_to='ampmedia/img')),
                ('projectName', models.CharField(max_length=20)),
                ('context', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'project',
                'verbose_name_plural': 'projects',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=20)),
                ('content', models.TextField(max_length=120)),
            ],
            options={
                'verbose_name': 'service',
                'verbose_name_plural': 'services',
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='New', max_length=35)),
                ('img2', models.ImageField(upload_to='ampmedia/img')),
                ('img', models.ImageField(upload_to='ampmedia/img')),
                ('subTitle2', models.CharField(max_length=35)),
                ('title2', models.CharField(max_length=70)),
                ('title', models.CharField(max_length=70)),
                ('description2', models.TextField()),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Slide',
                'verbose_name_plural': 'Slides',
            },
        ),
        migrations.CreateModel(
            name='TermsAndCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('introduction', models.TextField(max_length=550)),
                ('use_of_site', models.TextField(max_length=550)),
                ('intel_property', models.TextField(max_length=550)),
                ('user_content', models.TextField(max_length=550)),
                ('liability', models.TextField(max_length=550)),
                ('indemnification', models.TextField(max_length=550)),
                ('modification', models.TextField(max_length=550)),
                ('law', models.TextField(max_length=550)),
                ('date', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Term',
                'verbose_name_plural': 'Our Terms',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='New', max_length=35)),
                ('clientProfession', models.CharField(max_length=50)),
                ('img', models.ImageField(upload_to='ampmedia/img')),
                ('rating', models.PositiveIntegerField(default=5)),
                ('clientName', models.CharField(max_length=20)),
                ('feedBack', models.TextField(max_length=120)),
            ],
            options={
                'verbose_name': 'testimony',
                'verbose_name_plural': 'testimonial',
            },
        ),
        migrations.CreateModel(
            name='TitleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favicon', models.ImageField(upload_to='ampmedia/favicon')),
                ('secondSlideSubTitle', models.CharField(max_length=50)),
                ('firstSlideSubTitle', models.CharField(max_length=50)),
                ('testimonySubTitle', models.CharField(max_length=50)),
                ('secondSlideTitle', models.CharField(max_length=70)),
                ('firstSlideTitle', models.CharField(max_length=70)),
                ('contactSubTitle', models.CharField(max_length=50)),
                ('projectSubTitle', models.CharField(max_length=50)),
                ('serviceSubTitle', models.CharField(max_length=50)),
                ('testimonyTitle', models.CharField(max_length=70)),
                ('footerSubTitle', models.CharField(max_length=50)),
                ('aboutSubTitle', models.CharField(max_length=50)),
                ('staffSubTitle', models.CharField(max_length=50)),
                ('studentTitle', models.CharField(max_length=70)),
                ('blogSubTitle', models.CharField(max_length=50)),
                ('contactTitle', models.CharField(max_length=70)),
                ('projectTitle', models.CharField(max_length=70)),
                ('serviceTitle', models.CharField(max_length=70)),
                ('privacyTitle', models.CharField(max_length=70)),
                ('searchTitle', models.CharField(max_length=50)),
                ('footerTitle', models.CharField(max_length=70)),
                ('staffTitle', models.CharField(max_length=70)),
                ('aboutTitle', models.CharField(max_length=70)),
                ('termsTitle', models.CharField(max_length=70)),
                ('pageTitle', models.CharField(max_length=50)),
                ('blogTitle', models.CharField(max_length=70)),
                ('faqTitle', models.CharField(max_length=70)),
            ],
            options={
                'verbose_name': 'Title',
            },
        ),
        migrations.CreateModel(
            name='StudentsRegisterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentType', models.CharField(choices=[('IT', 'IT student'), ('nonIT', 'non-IT student')], max_length=5)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('image', models.ImageField(upload_to='ampmedia/students')),
                ('occupation', models.CharField(max_length=200)),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('phone', models.IntegerField()),
                ('address', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('courseOfStudy', models.ManyToManyField(related_name='my_courses', to='new_hightech.courses')),
            ],
            options={
                'verbose_name': 'student',
                'verbose_name_plural': 'students',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram_handle', models.URLField(blank=True, null=True)),
                ('linkedin_handle', models.URLField(blank=True, null=True)),
                ('facebook_handle', models.URLField(blank=True, null=True)),
                ('twitter_handle', models.URLField(blank=True, null=True)),
                ('github_handle', models.URLField(blank=True, null=True)),
                ('img', models.ImageField(upload_to='ampmedia/img')),
                ('is_active', models.BooleanField(default=True)),
                ('fullName', models.CharField(max_length=100)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new_hightech.position')),
            ],
            options={
                'verbose_name': 'staff',
                'verbose_name_plural': 'personel',
            },
        ),
        migrations.CreateModel(
            name='Share',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sharedDate', models.DateTimeField(auto_now_add=True)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new_hightech.blog')),
            ],
        ),
        migrations.CreateModel(
            name='Privacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choices_rights', models.TextField(max_length=550)),
                ('personal_data', models.TextField(max_length=550)),
                ('policy_update', models.TextField(max_length=550)),
                ('info_context', models.TextField(max_length=550)),
                ('third_party', models.TextField(max_length=550)),
                ('use_of_info', models.TextField(max_length=550)),
                ('usage_data', models.TextField(max_length=550)),
                ('info_share', models.TextField(max_length=550)),
                ('cookies', models.TextField(max_length=550)),
                ('security', models.TextField(max_length=550)),
                ('name', models.CharField(max_length=20)),
                ('date', models.DateField(auto_now=True)),
                ('introduction', models.TextField()),
                ('info_share_li', models.ManyToManyField(related_name='info_share_points', to='new_hightech.point')),
                ('use_of_info_li', models.ManyToManyField(related_name='use_of_info_points', to='new_hightech.point')),
            ],
            options={
                'verbose_name': 'Private',
                'verbose_name_plural': 'Privacy',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commenterName', models.CharField(max_length=50)),
                ('commentText', models.TextField()),
                ('commentedDate', models.DateTimeField(auto_now_add=True)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new_hightech.blog')),
            ],
        ),
    ]
