from webapps.new_hightech.models.title import *
from webapps.new_hightech.models.baseModel import *
from webapps.new_hightech.models.serviceModel import *
from webapps.new_hightech.models.aboutModel import *
from webapps.new_hightech.models.projectModel import *
from webapps.new_hightech.models.staffModel import *
from webapps.new_hightech.models.blogModel import *
from webapps.new_hightech.models.contactModel import *
from webapps.new_hightech.models.testimonialModel import *
from webapps.new_hightech.models.footerModel import *
from webapps.new_hightech.models.privacyModel import *
from webapps.new_hightech.models.faqModel import *
from webapps.new_hightech.models.termsModel import *
from webapps.new_hightech.models.advertModel import *
from webapps.new_hightech.models.studentModel import *
